name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (root)
        run: npm ci

      - name: Install functions deps
        run: |
          cd functions
          npm ci

      - name: Run unit/integration tests
        run: npm run test:ci

      - name: Build Storybook (smoke)
        run: npm run build-storybook

      - name: Build app
        run: npm run build

      - name: Upload production build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build
          if-no-files-found: error

  deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build

      - name: Firebase Auth
        uses: firebase/actions/login@v1
        with:
          service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}

      - name: Deploy Hosting + Functions (if any changes)
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting,functions --non-interactive --project $FIREBASE_PROJECT_ID
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
